name: task

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: "1"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        
      - name: "Running Task"
        run: |
          cd ${GITHUB_WORKSPACE}/
          go run main.go
          
      - name: "Commit new data"
        run: |
          git config user.name "${{ secrets.gh_USER }}"
          git config user.email "${{ secrets.gh_USER }}@users.noreply.github.com"
          git add .
          git commit -am "Update README.md"
          git push --all -f https://${{ secrets.gh_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
